### ISSUE TITLE
Incorrect documentation on what transactions can be signed?

### ISSUE THREAD

**Issue by Ronserruya** [lenondupe/ledger-app-stellar#12]
From https://github.com/lenondupe/ledger-app-stellar/blob/master/doc/stellarapp.md

> The application covers the following functionalities on ed25519:
   Retrieve a public Stellar address given a BIP 32 path
   Sign a single Stellar payment transaction given a BIP 32 path and a stellar transaction xdr
   Sign any Stellar transaction given a BIP 32 path and a transaction hash

From my understanding, you can sign using the XDR only for a transaction that contains a single payment operation. Or sign using a hash for any transaction whatsoever.

I just tried that yet it looks like I can sign with the XDR for transactions that Include multiple payments operations, and even other types of operations. Should the doc be fixed or did I misunderstood something?

Using https://www.stellar.org/laboratory/#?network=test
Ledger nano s: Secure element 1.4.2, MCU 1.5
Stellar ledger app: 3.0

**Comment by Akuukis** [comment]
Right, that was added at v3.0 ([changelog](https://github.com/lenondupe/ledger-app-stellar/blob/master/release-notes.md)), so docs should be updated.

**Comment by lenondupe** [comment]
Yes that document is way outdated. I'm not sure if it adds sufficient value to maintain it.

**Comment by lenondupe** [comment]
Removed the doc
