### ISSUE TITLE
Display network transaction is signed for

### ISSUE THREAD

**Issue by bartekn** [lenondupe/ledger-app-stellar#2]
https://github.com/lenondupe/ledger-app-stellar/blob/master/src/xdr_parser.c#L161

I think you should display network ID (in case tx signing). It's very important.

**Comment by lenondupe** [comment]
I just looked into this. Unfortunately it seems that the network id that is encoded in the xdr is the sha256 hashed value of the network passpharse so showing that to the user I think would not be very informative.

**Comment by lenondupe** [comment]
Of course. That is a good idea.
