### ISSUE TITLE
For hash signing app should display hash

### ISSUE THREAD

**Issue by bartekn** [lenondupe/ledger-app-stellar#3]
Currently only a warning is displayed according to docs:
> This command signs any Stellar transaction given a transaction hash. The user is warned there is no data available to inspect.

**Comment by lenondupe** [comment]
Great idea! Why didn't I think of that?

**Comment by lenondupe** [comment]
I've implemented displaying a hash summary, similar to the way an address summary is shown. I.e. not the entire thing, but only the first few and the last few bytes.

**Comment by bartekn** [comment]
Can we show the whole thing? I've seen some apps scroll longer strings.

**Comment by lenondupe** [comment]
I don't think that would increase usability. But I do think it would decrease it. I mean, it would be possible, but perhaps not desirable. (I see the Ethereum app displays the destination address in 10 steps. Given that an Ethereum address is 40 characters long and a sha156 hash 128 characters you'd be looking at triple that amount for displaying the hash)

If the argument comes down to the possibility of a collision we can go into a little detail and try to calculate that possibility. I currently display 6 bytes. 6 bytes is 6*8 = 48 bits is 2^48 different outputs. If I understand SHA hashing correctly we can expect a uniform distribution of outputs given any set of inputs. This leads me to believe that the chance of collision is 1 in 2^48. I find that a small enough number to justify sacrificing some exactness in favour of usability.
